# 修改TNAME: CR660x 中的CR660x为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id # 自己点的 Star

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |                         # 安装依赖包
        sudo apt-get update
        sudo apt-get -y install libtool-bin gperf python3-docutils autopoint gettext
        sudo timedatectl set-timezone 'Asia/Shanghai'  # 设置时区
    - name: Clone source code
      run: |                         # 克隆源码
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
    - name: Run shellcheck
      run: |                         # 运行 shellcheck
        cd /opt/rt-n56u
        sh ./trunk/tools/shellcheck.sh
    - name: Prepare toolchain
      run: |                         # 准备工具链
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: CR660x
      run: |                         # 开始编译固件
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        ################################################################################################
        # 因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPUMP/d' configs/templates/$TNAME.config # 用于抓包的 tcpdump
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' configs/templates/$TNAME.config # EAP-TTLS 和 EAP-PEAP 身份验证支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' configs/templates/$TNAME.config # SFTP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' configs/templates/$TNAME.config # OpenSSH
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' configs/templates/$TNAME.config # OPENVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC/d' configs/templates/$TNAME.config # 椭圆曲线（EC）
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE/d' configs/templates/$TNAME.config # OpenSSL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' configs/templates/$TNAME.config # 用于IPTV的XUPNPD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' configs/templates/$TNAME.config # ffmpeg
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CURL/d' configs/templates/$TNAME.config # CURL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' configs/templates/$TNAME.config # 用于Drcom的工具DOGCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' configs/templates/$TNAME.config # 用于二级路由、教育网分发IPv6地址的NAPT66
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' configs/templates/$TNAME.config # 用于KMS的VLMCSD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' configs/templates/$TNAME.config # 网页终端模拟器TTYD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' configs/templates/$TNAME.config # HTOP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' configs/templates/$TNAME.config # NANO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' configs/templates/$TNAME.config # IPERF3
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' configs/templates/$TNAME.config # MTR
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' configs/templates/$TNAME.config # SOCAT
        ######################################################################
        # 以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_TCPUMP=n" >> configs/templates/$TNAME.config # 删除用于抓包的 tcpdump
        echo "CONFIG_FIRMWARE_INCLUDE_EAP_PEAP=n" >> configs/templates/$TNAME.config # 删除 EAP-TTLS 和 EAP-PEAP 身份验证支持
        echo "CONFIG_FIRMWARE_INCLUDE_SFTP=n" >> configs/templates/$TNAME.config # 删除 SFTP
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSH=n" >> configs/templates/$TNAME.config # 删除 OpenSSH
        echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=n" >> configs/templates/$TNAME.config # 删除OPENVPN
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC=n" >> configs/templates/$TNAME.config # 删除椭圆曲线（EC）
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n" >> configs/templates/$TNAME.config # 删除 OpenSSL
        echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> configs/templates/$TNAME.config # 删除用于IPTV的XUPNPD
        echo "CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n" >> configs/templates/$TNAME.config # 删除 ffmpeg
        echo "CONFIG_FIRMWARE_INCLUDE_CURL=n" >> configs/templates/$TNAME.config # 删除 CURL
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> configs/templates/$TNAME.config # 删除用于Drcom的工具DOGCOM
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> configs/templates/$TNAME.config # 删除用于二级路由、教育网分发IPv6地址的NAPT66
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> configs/templates/$TNAME.config # 删除用于KMS的工具VLMCSD
        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=n" >> configs/templates/$TNAME.config # 删除网页终端模拟器TTYD
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> configs/templates/$TNAME.config # HTOP
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> configs/templates/$TNAME.config # NANO
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> configs/templates/$TNAME.config # IPERF3
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> configs/templates/$TNAME.config # MTR
        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> configs/templates/$TNAME.config # SOCAT
        # 如果 /opt/rt-n56u/trunk 目录中不存在 .config 文件，先执行清理脚本 ./clear_tree，后编译的话，执行清理时会报错
        # Project config file .config not found! Terminate.
        #cp -f configs/templates/$TNAME.config .config
        # 修改默认默认网关
        sed -i 's/192.168.2.1/192.168.123.1/g' user/shared/defaults.h
        sed -i 's/192.168.2.100/192.168.123.100/g' user/shared/defaults.h
        sed -i 's/192.168.2.244/192.168.123.244/g' user/shared/defaults.h
        # 修改后台地址中的相关192.168.2.1 
        sed -i 's/192.168.2.1/192.168.123.1/g' user/www/n56u_ribbon_fixed/Restarting.asp
        sed -i 's/192.168.2.1/192.168.123.1/g' user/www/dict/EN.footer
        sed -i 's/192.168.2.1/192.168.123.1/g' user/www/dict/CN.dict
        # 编译
        sudo ./build_firmware_ci $TNAME
        sudo mv -f images/*.trx /opt/images/
        # 清理
        sudo ./clear_tree
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
